AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  # Wrapper function for all financial functions
  EFFECT:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'lambda_handlers.generic_financial_function_handler'
      CodeUri: '../financial_functions'
      Runtime: 'python3.6'
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          LOG_LEVEL: INFO
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/financial_functions/wrapper'
            Method: post
